arantes:
    client:
        address:
            url: http://localhost:8082/addresses

spring:
    application:
        name: authentication
    data:
        mongodb:
            uri: mongodb://localhost:27017/hexagonal